name: Setup NPM Packages
description: Setup required NPM packages with caching for pnpm
runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/pnpm-packages@
    with:
      frozen: 'true'
      ignore-scripts: 'true'
      paths: |
        .
        website
