name: Setup NPM Packages
description: Setup required NPM packages with caching for pnpm
runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/pnpm-packages@d0d44d296e8a29197b8ce7c9c692ecc6440b3045
    with:
      frozen: 'true'
      ignore-scripts: 'true'
      paths: |
        .
        website
