name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@d0d44d296e8a29197b8ce7c9c692ecc6440b3045
    with:
      plugins: |
        picotools=https://github.com/egose/picotools.git

  - name: Install python tools
    run: |
      pip install -r requirements.txt
      asdf reshim
    shell: bash
