name: 11.Run pre-commit

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-npm

    - name: Run pre-commit
      uses: egose/actions/precommit@05df4c6833f0542c16f2a8ab90022fbd4a1a4c6b
      with:
        config: .pre-commit-config.yaml
        commit-on-push: false
        commit-on-pr: false
