name: Check code/commit conventions

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-npm

    - name: Run pre-commit
      uses: egose/actions/pre-commit@d0d44d296e8a29197b8ce7c9c692ecc6440b3045
      with:
        config: .pre-commit-config.yaml
        commit-on-push: true
        commit-on-pr: false
